config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :authors
      resources :books
    end
  end
  
  root to: 'main#index'
  resources :authors
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    self.primary_key = "author_id"
    has_many :author_books, dependent: :delete_all
    has_many :books, through: :author_books

    validates :author_id, presence: true, uniqueness: true
    validates :first_name, presence: true
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
    belongs_to :author
    belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
    self.primary_key = "book_id"

    has_many :author_books, dependent: :delete_all
    has_many :authors, through: :author_books

    validates :book_id, presence: true, uniqueness: true
    validates :book_title, presence: true, uniqueness: true
end

app/controllers/api/v1/authors_controller.rb
module Api
    module V1
      class AuthorsController < ApplicationController
        rescue_from ActiveRecord::RecordInvalid, with: :show_errors
        rescue_from ActiveRecord::RecordNotFound, with: :show_errors
        skip_before_action :verify_authenticity_token
        before_action :set_author, only: %i[ show edit update destroy ]
        
        def index
            render json: Author.all
        end

        def create
            @author = Author.create!(author_params)
            render json: {
                author: @author
            }
        end

        def update
            @author.update(author_params)
            head :no_content
        end

        def show
            book_ids = AuthorBook.where(author_id: params[:id]).pluck('book_id')
            books = Book.where(book_id: book_ids).pluck('book_title')
            render json:{"author_details": Author.find(params[:id]),
                 "books": books}
        end

        def destroy
            @author.destroy
            head :no_content
        end

        def set_author
            @author = Author.find(params[:id])
        end
    
        def author_params
            params.permit(:author_id, :first_name, :last_name, :date_of_birth)
        end
      end
    end
  end

app/controllers/api/v1/books_controller.rb
module Api
    module V1
      class BooksController < ApplicationController
        rescue_from ActiveRecord::RecordInvalid, with: :show_errors
        rescue_from ActiveRecord::RecordNotFound, with: :show_errors
        skip_before_action :verify_authenticity_token
        before_action :set_book, only: [:show, :edit, :destroy, :update]
        def index
            render json: Book.all
        end

        def create
          @book = Book.create!(book_params)
          render json: {
            book: @book
          }
        end

        
        def update
          @book.update(book_params)
          head :no_content
        end

        def show
          author_ids = AuthorBook.where(book_id: params[:id]).pluck('author_id')
          authors = Author.where(author_id: author_ids).pluck('first_name')
          render json:{"book_details": Book.find(params[:id]),
               "authors": authors}
        end

        def destroy
          @book.destroy
          head :no_content
        end

        private

        def set_book
            @book = Book.find(params[:id])
        end

        def book_params
            params.permit(:book_id, :book_title)
        end
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Response
  def show_errors(exception)
    if exception.class == ActiveRecord::RecordNotFound
      json_response({ message: exception.message }, :not_found)
    else
      json_response({ message: exception.message }, :unprocessable_entity)
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :set_author, only: %i[ show edit update destroy ]

    def index
      @authors = Author.all
    end
  
    def show
    end
  
    def new
      @author = Author.new
      # @books= Book.all.pluck(:book_title)
    end
  
    def edit
    end
  
    def create
      @author = Author.new(author_params)
      unless author_params[:date_of_birth].empty?
        @author.date_of_birth = DateTime.parse(author_params[:date_of_birth])
      end

        if @author.save
          redirect_to @author
        else
          render :new
        end
    end

    def update
        if @author.update(author_params)
          redirect_to @author
        else
          render :edit
        end
    end
  
    def destroy
      @author.destroy
      redirect_to authors_path

    end
  
    private

      def set_author
        @author = Author.find(params[:id])
      end
  
      def author_params
        params.require(:author).permit(:author_id, :first_name, :last_name, :date_of_birth)
      end
  end
  

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    before_action :set_book, only: [:show, :edit, :destroy, :update]

    def index
        @books = Book.all
    end

    def show
    end

    def edit
    end

    def update
        if @book.update(book_params)
            authors = params[:book][:authors]
            authors = authors.reject { |author| author.empty? }
            @book.authors = []
            authors.each do |author|
            @book.authors << Author.find_by(first_name: author) unless @book.authors.include?(Author.find_by(first_name: author))
          end
            redirect_to @book
        else
            render 'edit'
        end
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        if @book.save
          authors = params[:book][:authors]
          authors = authors.reject { |author| author.empty? }
          authors.each do |author|
            @book.authors << Author.find_by(first_name: author)
          end
          redirect_to @book
        else
          render :new
        end
    end

    def destroy
        @book.destroy
        redirect_to books_path
    end

    private

    def set_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:book_id, :book_title, :authors)
    end


end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
    extend ActiveSupport::Concern
  
    included do
      rescue_from ActiveRecord::RecordNotFound do |e|
        json_response({ message: e.message }, :not_found)
      end
  
      rescue_from ActiveRecord::RecordInvalid do |e|
        json_response({ message: e.message }, :unprocessable_entity)
      end
    end
  end
  

app/controllers/concerns/response.rb
# app/controllers/concerns/response.rb
module Response
    def json_response(object, status = :ok)
      render json: object, status: status
    end
end
  

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: author) do |form| %>
        <% if author.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
            <ul>
              <% author.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <div class="col-10">
          <%= form.number_field :author_id, class: "form-control shadow rounded", placeholder: "Author ID" %>
        </div>
        <br/>
        <div class="mb-3">  
          <div class="col-10">
          <%= form.text_field :first_name, class: "form-control shadow rounded", placeholder: "First Name" %>
        </div>
        <br/>
        <div class="mb-3">
          <div class="col-10">
          <%= form.text_field :last_name, class: "form-control shadow rounded", placeholder: "Last Name" %>
        </div>
        <br/>
        <div class="mb-3">
          <div class="col-10">
          <%= form.text_field :date_of_birth, class: "form-control shadow rounded", placeholder: "Date of Birth (dd-mm-yyyy)" %>
        </div>
        <br/>
        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Author</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Date of Birth</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.author_id %></td>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= author.date_of_birth %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

app/views/authors/show.html.erb
<p>
  <strong>Author:</strong>
  <%= @author.author_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Books:</strong>
  <% if @author.books%>
  <% @author.books.each do |book| %>
  <%= link_to book.book_title, book %> |
  <%end%>
  <%end%>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: book) do |form| %>
        <% if book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
            <ul>
              <% book.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <div class="col-10">
          <%= form.number_field :book_id, class: "form-control shadow rounded", placeholder: "Book ID" %>
        </div>
        <br/>
        <div class="mb-3">  
          <div class="col-10">
          <%= form.text_field :book_title, class: "form-control shadow rounded", placeholder: "Book Title" %>
        </div>
        <br/>
        <%= form.select(:authors, Author.all.pluck('first_name'),{ :prompt => "Please select"},
                                  { :multiple => true, :size => 5 }
        ) %>
        <div class="actions">
          <%= form.submit %>
        </div>

      <% end %>
      </div>
  </div>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>
<div class="col-10">
    <%= link_to 'Show', @book %>|
    <%= link_to 'Back', books_path %>
<div>

app/views/books/index.html.erb
<h1>Books</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Book Id</th>
      <th>Book Title</th>
      <th>Authors</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_id %></td>
        <td><%= book.book_title %></td>
        <td>
          <% if book.authors%>
          <% book.authors.each do |author| %>
          <%= link_to author.first_name, author %><br>
          <%end%>
          <%end%>
        </td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book, authors: @authors %>

app/views/books/show.html.erb
<p>
  <strong>Book ID:</strong>
  <%= @book.book_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.book_title %>
</p>

<p>
  <strong>Authors:</strong>
  <% if @book.authors%>
  <% @book.authors.each do |author| %>
  <%= link_to author.first_name, author %> |
  <%end%>
  <%end%>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Library', root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Authors', authors_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Books', books_path, class: "nav-link active"%>
        </li>
        </li>
      </ul>
      <form class="d-flex">
      </form>
    </div>
  </div>
</nav>